name: Build and deploy to GitHub Pages

on:
  workflow_run:
    workflows:
      - Run Tests
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4
      - name: Build Jekyll for GitHub Pages
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./docs
          destination: ./docs/_site
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: on-success
    steps: 
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment