name: Run Tests

on:
  push:
    {}
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sdkman/sdkman-action@b1f9b696c79148b66d3d3a06f7ea801820318d0f
        id: sdkman
      - name: Run tests
        run: |
          export JAVA_HOME=$(sdk home java 21.0.1-tem) 
          mvn clean test

  example-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sdkman/sdkman-action@b1f9b696c79148b66d3d3a06f7ea801820318d0f
        id: sdkman
      - name: Gauge install
        run: |
          curl -SsL https://downloads.gauge.org/stable | sh
      - name: Run tests
        run: |
          export JAVA_HOME=$(sdk home java 21.0.1-tem)
          mvn clean install -Dgpg.skip
          cd examples/simple-api-test
          mvn test